# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.0.x'
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGetPackages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration) $(buildNumber)'
  inputs:
    command: 'build'
    projects: 'src/Blog.Web/Blog.Web.csproj'
    arguments: '--configuration $(buildConfiguration) /p:Version=$(buildNumber)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet test $(testConfiguration)'
  inputs:
    command: 'test'
    projects: 'test/**/*.csproj'
    arguments: '--configuration $(testConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  displayName: dotnet publish $(buildConfiguration)
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'BlogStaging'
    publishLocation: 'Container'