# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  displayName: 'Set correct version'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Generating Build Number"
      $baseDate = [datetime]"01/01/2000"
      $currentDate = $(Get-Date)
      $interval = NEW-TIMESPAN –Start $baseDate –End $currentDate
      $days = $interval.Days
      
      Write-Host "##vso[task.setvariable variable=buildNumber]0.0.$days.1024"
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGetPackages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'src/Blog.Web/Blog.Web.csproj'
    arguments: '--configuration $(buildConfiguration) /p:Version=$(buildNumber)'
- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    projects: 'test/**/*.csproj'
    arguments: '--configuration $(testConfiguration)'