# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
# - script: npm --prefix src/Blog.Web install
#   displayName: Install npm packages 
- script: dotnet restore Blog.sln
  displayName: Restore NuGet packages
- script: dotnet build Blog.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
